version: '3.7'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: baseDock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - 5432:5432
